"""empty message

Revision ID: 005926094705
Revises: 97df6af4309e
Create Date: 2021-11-02 17:46:19.511827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '005926094705'
down_revision = '97df6af4309e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_basic', 'account',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user_basic', 'password',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user_basic', 'salt',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.create_unique_constraint(None, 'user_basic', ['account'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_basic', type_='unique')
    op.alter_column('user_basic', 'salt',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user_basic', 'password',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user_basic', 'account',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
