"""empty message

Revision ID: 86d59038aa5c
Revises: 
Create Date: 2021-11-01 18:40:09.752520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86d59038aa5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user3',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=16), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('user2')
    op.drop_table('user1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user1',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('account', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user2',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('account', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('user3')
    # ### end Alembic commands ###
