"""empty message

Revision ID: c3b98818affb
Revises: dcd53e0ff0a6
Create Date: 2021-11-02 16:18:20.682811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3b98818affb'
down_revision = 'dcd53e0ff0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_basic',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_basic_2',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_basic_3',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=16), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('user3')
    op.drop_table('user2')
    op.drop_table('user1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user1',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('account', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user2',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('account', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user3',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('account', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_basic_3')
    op.drop_table('user_basic_2')
    op.drop_table('user_basic')
    # ### end Alembic commands ###
